import psycopg

class DatabaseConnector:
    def __init__(self, db_params: dict):
        self.dbparams= db_params
        self._check_tables_exists()

    def _get_connection(self):
        return psycopg.connect(**self.dbparams)

    def _check_tables_exists(self):
        with self._get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("""CREATE TABLE IF NOT EXISTS iss_data
                        (   name TEXT,
                            id INT,
                            latitude FLOAT,
                            longitude FLOAT,
                            altitude FLOAT,
                            velocity FLOAT,
                            visibility TEXT,
                            footprint FLOAT,
                            timestamp INT,
                            daynum FLOAT,
                            solar_lat FLOAT,
                            solar_lon FLOAT,
                            units TEXT,
                            uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                        )""")
                cursor.execute("""CREATE TABLE IF NOT EXISTS human_readable_table
                        (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            readable_log TEXT,
                            traveled_distance TEXT
                        )""")

    def insert_in_raw_table(self, data_dict: dict):

        with self._get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("""INSERT INTO iss_data (name, id, latitude, longitude, altitude, velocity, visibility,
                                                         footprint, timestamp, daynum, solar_lat, solar_lon, units) 
                                  VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING *""",
                               (data_dict["name"], data_dict["id"],
                                data_dict["latitude"], data_dict["longitude"],
                                data_dict["altitude"], data_dict["velocity"],
                                data_dict["visibility"], data_dict["footprint"],
                                data_dict["timestamp"], data_dict["daynum"],
                                data_dict["solar_lat"], data_dict["solar_lon"], data_dict["units"]) )
                conn.commit()

    def insert_in_human_table(self, readable_log: str, traveled_distance: str):
        with self._get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("""INSERT INTO human_readable_table (readable_log, traveled_distance)
                                  VALUES (%s, %s) """, (readable_log, traveled_distance))
            conn.commit()

    def get_latest_timestamp(self):
        with self._get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("""SELECT timestamp
                                  FROM iss_data
                                  ORDER BY timestamp DESC LIMIT 1;""")
                row = cursor.fetchone()
                return row[0] if row else 0

    def get_last_elapsed_seconds(self) -> int:
        with self._get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("""
                               SELECT timestamp
                               FROM iss_data
                               ORDER BY timestamp DESC
                                   LIMIT 2
                               """)
                rows = cursor.fetchall()
                if len(rows) < 2:
                    return 0

                latest_ts = rows[0][0]
                previous_ts = rows[1][0]
                return latest_ts - previous_ts

    def often_visibility(self):
        with self._get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("""SELECT visibility
                                  FROM iss_data
                                  GROUP BY visibility
                                  ORDER BY COUNT(*) DESC LIMIT 1;""")
                return cursor.fetchone()[0]

    def last_velocity(self):
        with self._get_connection() as conn:
            with conn.cursor() as cursor:
                cursor.execute("""SELECT velocity
                                  FROM iss_data
                                  ORDER BY uid DESC LIMIT 1;""")
                return cursor.fetchone()[0]