import requests
import os
from dotenv import load_dotenv
import logging
import json
from time import perf_counter, sleep
import psycopg


load_dotenv()

ISS_API=os.getenv("ISS_API_KEY")
GEO_LOCATOR_API_KEY = os.getenv("GEO_LOCATOR_API_KEY")

logging.basicConfig(level=logging.INFO)

db_config = {
    "dbname": os.getenv("DBNAME"),
    "user": os.getenv("USERNAME"),
    "password": os.getenv("PASSWORD"),
    "host": os.getenv("HOST"),
    "port": os.getenv("PORT", 5432)
}

class IssRequest:
    def __init__(self, _iss_api_endpoint):
        self.response = requests.get(_iss_api_endpoint)


class JsonFetcher:
    def __init__(self, file_name, _iss_api_endpoint):
        self.file_name = file_name
        self.latitude = None
        self.longitude = None
        self.velocity = None
        self.iss_api_endpoint = _iss_api_endpoint

    def _json_write(self):
        with open(self.file_name, "a", encoding="utf-8") as file:
            file.write(json.dumps(self.iss_api_endpoint.json(), ensure_ascii=False) + "\n")

    def _extract_location(self):
        with open(self.file_name, "r+", encoding="utf-8") as file:
            json_rows = file.readlines()
            self.json_dict = json.loads(json_rows[-1])

class GeoLocation:
    def __init__(self, latitude, longitude, velocity, _GEO_LOCATOR_API_KEY):
        self.latitude = latitude
        self.longitude = longitude
        self.velocity = velocity
        self.GEO_LOCATOR_API_KEY = _GEO_LOCATOR_API_KEY
        self.country = None
        self.city = None
        self.ocean = None

    def _geo_location(self):
        location = requests.get(f"https://api.opencagedata.com/geocode/v1/json?q={self.latitude}+{self.longitude}&key="
                                f"{self.GEO_LOCATOR_API_KEY}")

        location_json = location.text
        locator_data = json.loads(location_json)

        first_parse = locator_data["results"][0]
        components = first_parse["components"]

        self.country = components.get("country")
        self.city = components.get("city")
        self.ocean = components.get("body_of_water")

    def print_geolocation(self):
        if self.ocean:
            # logging.info(f"The ISS is above {self.ocean}, it's current speed is {self.velocity} kmh")
            return f"The ISS is above {self.ocean}, it's current speed is {self.velocity} kmh"
        elif self.country and self.city:
            return f"The ISS is above {self.country}, {self.city}, it's current speed is {self.velocity} kmh"
        else:
            return f"The ISS is above {self.country}, it's current speed is {self.velocity} kmh"


class DatabaseConnection:
    def __init__(self, dbname, user, password, host, port):
        self.dbname = dbname
        self.user = user
        self.password = password
        self.host = host
        self.port = port

    def check_tables_exists(self):
        with (psycopg.connect(
            host=self.host,
            port=self.port,
            dbname=self.dbname,
            user=self.user,
            password=self.password)
        as conn):
            with conn.cursor() as cursor:
                cursor.execute("""CREATE TABLE IF NOT EXISTS iss_local
                        (   name TEXT,
                            id INT,
                            latitude FLOAT,
                            longitude FLOAT,
                            altitude FLOAT,
                            velocity FLOAT,
                            visibility TEXT,
                            footprint FLOAT,
                            timestamp INT,
                            daynum FLOAT,
                            solar_lat FLOAT,
                            solar_lon FLOAT,
                            units TEXT,
                            uid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                        )""")
                cursor.execute("""CREATE TABLE IF NOT EXISTS human_readable_table
                        (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            readable_log TEXT
                        )""")

    def insert_in_iss_table(self, data_dict: dict, readable_log: str):

        with (psycopg.connect(
            host=self.host,
            port=self.port,
            dbname=self.dbname,
            user=self.user,
            password=self.password)
        as conn):
            with conn.cursor() as cursor:
                cursor.execute("""INSERT INTO iss_local VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING *""",
                               (data_dict["name"], data_dict["id"],
                                data_dict["latitude"], data_dict["longitude"],
                                data_dict["altitude"], data_dict["velocity"],
                                data_dict["visibility"], data_dict["footprint"],
                                data_dict["timestamp"], data_dict["daynum"],
                                data_dict["solar_lat"], data_dict["solar_lon"], data_dict["units"]) )
                self.last_data = cursor.fetchone()
                cursor.execute("""INSERT INTO human_readable_table (readable_log)
                                  VALUES (%s) """, (readable_log,))
                # print (self.last_data)
                cursor.execute("""SELECT visibility FROM iss_local GROUP BY visibility 
                                    ORDER BY COUNT(*) DESC
                                    LIMIT 1;""")
                self.often_visibility = cursor.fetchone()[0]
            conn.commit()




if __name__ == "__main__":
    db_conn = DatabaseConnection(**db_config)
    db_conn.check_tables_exists()

    while True:
        start = perf_counter()

        iss_api_fetch = IssRequest(ISS_API).response
        iss_api_fetch.json()

        json_fetch = JsonFetcher("satelite_data.jsonl", iss_api_fetch)
        json_fetch._json_write()
        json_fetch._extract_location()

        geo_location = GeoLocation(iss_api_fetch.json()["latitude"], iss_api_fetch.json()["longitude"],
                                   iss_api_fetch.json()["velocity"], _GEO_LOCATOR_API_KEY=GEO_LOCATOR_API_KEY)
        geo_location._geo_location()


        db_conn.insert_in_iss_table(json_fetch.json_dict, geo_location.print_geolocation() )



        logging.info(geo_location.print_geolocation())

        print(f"The satellite is more often in the {db_conn.often_visibility} state ")

        end = perf_counter()
        print(end - start)
        sleep(90)