import requests
import os
from dotenv import load_dotenv
import logging
import json
from time import perf_counter, sleep
import psycopg
from psycopg.rows import dict_row


load_dotenv()

ISS_API=os.getenv("ISS_API_KEY")
GEO_LOCATOR_API_KEY = os.getenv("GEO_LOCATOR_API_KEY")

logging.basicConfig(level=logging.INFO)

db_config = {
    "dbname": os.getenv("DBNAME"),
    "user": os.getenv("USERNAME"),
    "password": os.getenv("PASSWORD"),
    "host": os.getenv("HOST"),
    "port": os.getenv("PORT", 5432)
}

class IssRequest:
    def __init__(self, _iss_api_endpoint):
        self.response = requests.get(_iss_api_endpoint)


class JsonFetcher:
    def __init__(self, file_name, _iss_api_endpoint):
        self.file_name = file_name
        self.latitude = None
        self.longitude = None
        self.velocity = None
        self.iss_api_endpoint = _iss_api_endpoint

    def _json_write(self):
        data_list = []

        if os.path.exists(self.file_name) and os.path.getsize(self.file_name) > 0:
            with open(self.file_name, "r", encoding="utf-8") as file:
                data_list = json.load(file)

        data_list.append(self.iss_api_endpoint.json())

        with open(self.file_name, "w", encoding="utf-8") as file:
            file.seek(0, 2)
            dmp = json.dump(data_list, file, indent=4)


    def _extract_location(self):
        with open(self.file_name, "r+", encoding="utf-8") as file:
            json_rows = json.load(file)
            json_rows_length = len(json_rows)

            self.latitude = json_rows[-1]["latitude"]
            self.longitude = json_rows[-1]["longitude"]
            self.altitude = json_rows[-1]["altitude"]
            self.velocity = json_rows[-1]["velocity"]
            self.visibility = json_rows[-1]["visibility"]
            self.footprint = json_rows[-1]["footprint"]
            self.timestamp = json_rows[-1]["timestamp"]
            self.daynum = json_rows[-1]["daynum"]
            self.solar_lat = json_rows[-1]["solar_lat"]
            self.solar_lon = json_rows[-1]["solar_lon"]
            self.units = json_rows[-1]["units"]

class GeoLocation:
    def __init__(self, latitude, longitude, velocity, _GEO_LOCATOR_API_KEY):
        self.latitude = latitude
        self.longitude = longitude
        self.velocity = velocity
        self.GEO_LOCATOR_API_KEY = _GEO_LOCATOR_API_KEY
        self.country = None
        self.city = None
        self.ocean = None

    def _geo_location(self):
        location = requests.get(f"https://api.opencagedata.com/geocode/v1/json?q={self.latitude}+{self.longitude}&key="
                                f"{self.GEO_LOCATOR_API_KEY}")

        location_json = location.text
        locator_data = json.loads(location_json)

        first_parse = locator_data["results"][0]
        components = first_parse["components"]

        self.country = components.get("country")
        self.city = components.get("city")
        self.ocean = components.get("body_of_water")

    def print_geolocation(self):
        if self.ocean:
            # logging.info(f"The ISS is above {self.ocean}, it's current speed is {self.velocity} kmh")
            return f"The ISS is above {self.ocean}, it's current speed is {self.velocity} kmh"
        elif self.country and self.city:
            return f"The ISS is above {self.country}, {self.city}, it's current speed is {self.velocity} kmh"
        else:
            return f"The ISS is above {self.country}, it's current speed is {self.velocity} kmh"


class DatabaseConnection:
    def __init__(self, dbname, user, password, host, port):
        self.dbname = dbname
        self.user = user
        self.password = password
        self.host = host
        self.port = port

    def check_tables_exists(self):
        with (psycopg.connect(
            host=self.host,
            port=self.port,
            dbname=self.dbname,
            user=self.user,
            password=self.password)
        as conn):
            with conn.cursor() as cursor:
                cursor.execute("""CREATE TABLE IF NOT EXISTS iss_locccallll
                        (   latitude FLOAT,
                            longitude FLOAT,
                            altitude FLOAT,
                            velocity FLOAT,
                            visibility TEXT,
                            footprint FLOAT,
                            timestamp INT,
                            daynum FLOAT,
                            solar_lat FLOAT,
                            solar_lon FLOAT,
                            units TEXT,
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                        )""")
                cursor.execute("""CREATE TABLE IF NOT EXISTS human_readable_table
                        (
                            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            readable_log TEXT
                        )""")

    def insert_in_iss_table(self, latitude, longitude, altitude, velocity, visibility, footprint, timestamp,
                     daynum, solar_lat, solar_lon, units):

        with (psycopg.connect(
            host=self.host,
            port=self.port,
            dbname=self.dbname,
            user=self.user,
            password=self.password)
        as conn):
            with conn.cursor() as cursor:
                cursor.execute("""INSERT INTO iss_locccallll VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING *""",
                               (latitude, longitude, altitude, velocity, visibility, footprint,
                                timestamp, daynum, solar_lat, solar_lon, units) )
                self.last_data = cursor.fetchone()
                print (self.last_data)
                cursor.execute("""SELECT visibility FROM iss_locccallll GROUP BY visibility 
                                    ORDER BY COUNT(*) DESC
                                    LIMIT 1;""")
                self.often_visibility = cursor.fetchone()[0]
            conn.commit()

    def insert_in_readable_table(self, text:str):
        with (psycopg.connect(
            host=self.host,
            port=self.port,
            dbname=self.dbname,
            user=self.user,
            password=self.password)
        as conn):
            with conn.cursor() as cursor:
                cursor.execute("""INSERT INTO human_readable_table (readable_log) VALUES (%s) """, (text, ))
            conn.commit()



if __name__ == "__main__":
    db_conn = DatabaseConnection(**db_config)
    db_conn.check_tables_exists()

    while True:
        start = perf_counter()
        iss_api_fetch = IssRequest(ISS_API).response
        iss_api_fetch.json()
        json_fetch = JsonFetcher("satelite_data.json", iss_api_fetch)
        json_fetch._json_write()
        json_fetch._extract_location()

        db_conn.insert_in_iss_table(json_fetch.latitude, json_fetch.longitude, json_fetch.altitude,json_fetch.velocity,
                             json_fetch.visibility, json_fetch.footprint,json_fetch.timestamp, json_fetch.daynum, json_fetch.solar_lat,
                             json_fetch.solar_lon, json_fetch.units)
        # db_conn.return_table()

        geo_location = GeoLocation(db_conn.last_data[0], db_conn.last_data[1],
                        db_conn.last_data[3], _GEO_LOCATOR_API_KEY = GEO_LOCATOR_API_KEY)
        geo_location._geo_location()
        logging.info(geo_location.print_geolocation())
        db_conn.insert_in_readable_table(geo_location.print_geolocation())

        print(f"The satellite is more often in the {db_conn.often_visibility} state ")

        end = perf_counter()
        print(end - start)
        sleep(5)